### ISSUE TITLE
[proposal] add github actions to templates

### ISSUE THREAD

**Issue by sw-yx** [jaredpalmer/tsdx#438]
### Current Behavior

gh actions are awesome. lets recommend and auto scaffold some for people to test their tsdx libraries? i know not everybody uses github but they could just delete the .github folder if so.

pull some from https://github.com/sdras/awesome-actions

what actions would people like?

e.g. i'd like matrix testing by default, as well as issue/pr templates

**Comment by ambroseus** [comment]
action for caching  .npm  between builds:
```yaml
- uses: actions/cache@v1
   with:
      path: ~/.npm
      key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      restore-keys: |
      ${{ runner.os }}-node-
```
